@extends('layouts.main')

@section('title') Comics @endsection

@section('content')
    <div class="container py-100">
        <h1>WELCOME TO DC COMICS!</h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum recusandae accusamus debitis. Molestias ea delectus minus dicta laboriosam aut, sapiente dolorem sequi excepturi vitae possimus illum. Eveniet maxime molestias a cumque, incidunt assumenda neque excepturi harum! Quos porro architecto quia odit dolore. Blanditiis consequatur, delectus perferendis cumque omnis ullam repellendus architecto, maiores aliquid, sequi porro sapiente rem voluptatum odio! Eveniet, molestias, cum ea corrupti iure illum quidem aliquid inventore incidunt provident alias quo nam! Eaque ab reiciendis natus maxime, pariatur in laudantium aliquam fugit ut distinctio magni laboriosam vero nulla nobis at quae quos, commodi eveniet reprehenderit est velit quas. Quibusdam adipisci quis ratione accusantium reiciendis consequuntur facilis, ut inventore iure incidunt nesciunt. Quia, optio nobis! Molestiae sed molestias necessitatibus, animi nesciunt non dolores nulla doloribus accusantium nam ab voluptatum, sapiente incidunt excepturi. Labore doloribus nostrum at suscipit atque odit quisquam delectus ducimus cumque? Magnam, beatae, dolore quo iusto perspiciatis vel rerum eius, quia minima ipsum aspernatur. Numquam, magni. Recusandae nihil maiores, magnam totam expedita numquam! Fugit omnis dolores maxime perferendis libero aliquid sint ipsam beatae, eum exercitationem vel culpa deleniti voluptatibus aut molestiae veniam voluptate rerum corrupti dolorum. Odio ipsa, quos ullam veniam aut eligendi atque nostrum expedita, tempore excepturi dignissimos quisquam hic suscipit commodi beatae modi rerum? Necessitatibus laborum placeat consectetur blanditiis! Quibusdam sapiente ab vel tempore laborum commodi, provident nostrum et sequi aspernatur vero magnam est officia numquam ullam quaerat ut sunt molestiae recusandae? Repellat quibusdam ad voluptatibus a laboriosam nam laborum possimus facere eveniet aliquid libero iste voluptas quam ex quos numquam, consequuntur itaque reiciendis vero ducimus error dignissimos doloremque excepturi omnis. Expedita minus nulla dicta, temporibus distinctio ratione maxime rerum velit perspiciatis in quaerat? Laudantium corrupti fugiat nemo aperiam optio provident tempore temporibus, possimus vero minima eos dolore, eum est, incidunt ipsa? Quos, hic enim!</p>
    </div>
@endsection